### PR TITLE
added CRUD operations in PHP

### PR DESCRIPTION
**Pull request by PrajapatiAnkit**
i have discussed about the basic CRUD operations in PHP

### CODE REVIEW

**Review by himanshu-daga — CHANGES_REQUESTED** [review]
Thanks for contributing. Please add all the source files to the directory.

**Comment by PrajapatiAnkit** [comment]
OK ,. I will

**Comment by PrajapatiAnkit** [comment]
all the  source files added to the directory

**Comment by punit-agarwal** [comment]
Great job @PrajapatiAnkit

**Pull request merged**
