### PR TITLE
added cookie example

### PR DESCRIPTION
**Pull request by vyaspranjal33**

### CODE REVIEW

**Review by punit-agarwal — APPROVED** [review]

**Review by punit-agarwal — APPROVED** [review]

**Comment by punit-agarwal** [comment]
@vyaspranjal33 Thanks for contributing.
It would be just awesome if you put some demo as it would be easy for me to review.
For example, you may add screenshots of your localhost, displaying your work.

Great work. Looking forward to seeing more contributions from you.

**Comment by vyaspranjal33** [comment]
i am far away from my server so would not be able to put demo i hope u can understand :)

**Comment by punit-agarwal** [comment]
I'll merge for this time then.
Just make sure that you add these files to their respective folders.
Like user location track example should be put in folder `login', as it is a test case used for login.

**Review by punit-agarwal — CHANGES_REQUESTED** [review]
Add these files to login folder instead of the root folder.

**Review by punit-agarwal — APPROVED** [review]

**Pull request merged**
